import './globals.css'
import { Inter } from 'next/font/google'

import '../../public/assets/vendor/bootstrap/css/bootstrap.min.css';
import '../../public/assets/vendor/bootstrap-icons/bootstrap-icons.css';
import '../../public/assets/vendor/boxicons/css/boxicons.min.css';
import '../../public/assets/vendor/quill/quill.snow.css';
import '../../public/assets/vendor/quill/quill.bubble.css';
import '../../public/assets/vendor/remixicon/remixicon.css';
import '../../public/assets/vendor/simple-datatables/style.css';
import '../../public/assets/css/style.css';


import Aside from "@/components/layouts/Aside";
import Footer from "@/components/layouts/Footer";
import Header from "@/components/layouts/Header";
import Script from 'next/script';








const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'NiceAdmin Bootstrap Template Demo',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Aside />
        {children}
        <Footer />

        <Script src="@public/assets/vendor/apexcharts/apexcharts.min.js"  />
        <Script src="@public/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"  />
        <Script src="@public/assets/vendor/chart.js/chart.umd.js"  />
        <Script src="@public/assets/vendor/echarts/echarts.min.js"  />
        <Script src="@public/assets/vendor/quill/quill.min.js"  />
        <Script src="@public/assets/vendor/simple-datatables/simple-datatables.js"  />
        <Script src="@public/assets/vendor/tinymce/tinymce.min.js"  />
        <Script src="@public/assets/vendor/php-email-form/validate.js"  />


        <Script src="@public/assets/js/main.js" />
      </body>
    </html>
  )
}
